package logisticspipes.proxy.enderio;

import java.util.ArrayList;
import java.util.List;
import java.util.Set;

import logisticspipes.asm.ModVersionedClass;
import logisticspipes.proxy.interfaces.IEnderIOProxy;

import net.minecraft.tileentity.TileEntity;

import crazypants.enderio.machine.hypercube.HyperCubeRegister;
import crazypants.enderio.machine.hypercube.TileHyperCube;
import crazypants.enderio.machine.hypercube.TileHyperCube.IoMode;
import crazypants.enderio.machine.hypercube.TileHyperCube.SubChannel;
import crazypants.enderio.machine.transceiver.Channel;
import crazypants.enderio.machine.transceiver.ChannelType;
import crazypants.enderio.machine.transceiver.ServerChannelRegister;
import crazypants.enderio.machine.transceiver.TileTransceiver;

@ModVersionedClass(modId = "EnderIO", version = "1.7.10-2.3.0.409_beta", classData = EnderIOProxy.PREVCLASSDATA, classDataDev = EnderIOProxy.PREVCLASSDATADEV)
public class EnderIOProxy implements IEnderIOProxy {

	@Override
	public boolean isHyperCube(TileEntity tile) {
		return tile instanceof TileHyperCube;
	}

	@Override
	public boolean isTransceiver(TileEntity tile) {
		return tile instanceof TileTransceiver;
	}

	@Override
	public List<TileEntity> getConnectedHyperCubes(TileEntity tile) {
		List<TileHyperCube> cons = HyperCubeRegister.instance.getCubesForChannel(((TileHyperCube) tile).getChannel());
		List<TileEntity> tiles = new ArrayList<TileEntity>();
		for (TileHyperCube cube : cons) {
			if (cube != tile) {
				tiles.add(cube);
			}
		}
		return tiles;
	}

	@Override
	public List<TileEntity> getConnectedTransceivers(TileEntity tile) {
		TileTransceiver transceiver = (TileTransceiver) tile;
		List<TileEntity> tiles = new ArrayList<TileEntity>();
		Object channel = transceiver.getRecieveChannels(ChannelType.ITEM).toArray()[0];
		for (TileTransceiver t : ServerChannelRegister.instance.getIterator((Channel) channel)) {
			if (t == transceiver) {
				continue;
			}
			Set<Channel> receiveChannels = t.getRecieveChannels(ChannelType.ITEM);
			Set<Channel> sendChannels = t.getSendChannels(ChannelType.ITEM);
			if (receiveChannels.size() == 1 && sendChannels.size() == 1 && channel.equals(receiveChannels.toArray()[0]) && channel.equals(sendChannels.toArray()[0])) {
				tiles.add(t);
			}
		}
		return tiles;
	}

	@Override
	public boolean isSendAndReceive(TileEntity tile) {
		if (tile instanceof TileHyperCube) {
			return IoMode.BOTH == ((TileHyperCube) tile).getModeForChannel(SubChannel.ITEM);
		}
		if (tile instanceof TileTransceiver) {
			Set<Channel> receiveChannels = ((TileTransceiver) tile).getRecieveChannels(ChannelType.ITEM);
			Set<Channel> sendChannels = ((TileTransceiver) tile).getSendChannels(ChannelType.ITEM);
			return receiveChannels.size() == 1 && sendChannels.size() == 1 && receiveChannels.toArray()[0].equals(sendChannels.toArray()[0]);
		}
		return false;
	}

	@Override
	public boolean isEnderIO() {
		return true;
	}

	//Source for this was taken from: http://ci.thezorro266.com/job/LogisticsPipes-0.9-mc17-bc7/60/
	protected static final String PREVCLASSDATA = "yv66vgAAADIAlAEAKWxvZ2lzdGljc3BpcGVzL3Byb3h5L2VuZGVyaW8vRW5kZXJJT1Byb3h5BwAB" +
			"AQAQamF2YS9sYW5nL09iamVjdAcAAwEALWxvZ2lzdGljc3BpcGVzL3Byb3h5L2ludGVyZmFjZXMv" +
			"SUVuZGVySU9Qcm94eQcABQEAEUVuZGVySU9Qcm94eS5qYXZhAQA5Y3JhenlwYW50cy9lbmRlcmlv" +
			"L21hY2hpbmUvaHlwZXJjdWJlL1RpbGVIeXBlckN1YmUkSW9Nb2RlBwAIAQAyY3JhenlwYW50cy9l" +
			"bmRlcmlvL21hY2hpbmUvaHlwZXJjdWJlL1RpbGVIeXBlckN1YmUHAAoBAAZJb01vZGUBAD1jcmF6" +
			"eXBhbnRzL2VuZGVyaW8vbWFjaGluZS9oeXBlcmN1YmUvVGlsZUh5cGVyQ3ViZSRTdWJDaGFubmVs" +
			"BwANAQAKU3ViQ2hhbm5lbAEABjxpbml0PgEAAygpVgwAEAARCgAEABIBAAR0aGlzAQArTGxvZ2lz" +
			"dGljc3BpcGVzL3Byb3h5L2VuZGVyaW8vRW5kZXJJT1Byb3h5OwEAC2lzSHlwZXJDdWJlAQAoKExu" +
			"ZXQvbWluZWNyYWZ0L3RpbGVlbnRpdHkvVGlsZUVudGl0eTspWgEABHRpbGUBACVMbmV0L21pbmVj" +
			"cmFmdC90aWxlZW50aXR5L1RpbGVFbnRpdHk7AQANaXNUcmFuc2NlaXZlcgEANmNyYXp5cGFudHMv" +
			"ZW5kZXJpby9tYWNoaW5lL3RyYW5zY2VpdmVyL1RpbGVUcmFuc2NlaXZlcgcAGwEAFmdldENvbm5l" +
			"Y3RlZEh5cGVyQ3ViZXMBADcoTG5ldC9taW5lY3JhZnQvdGlsZWVudGl0eS9UaWxlRW50aXR5OylM" +
			"amF2YS91dGlsL0xpc3Q7AQA2Y3JhenlwYW50cy9lbmRlcmlvL21hY2hpbmUvaHlwZXJjdWJlL0h5" +
			"cGVyQ3ViZVJlZ2lzdGVyBwAfAQAIaW5zdGFuY2UBADhMY3JhenlwYW50cy9lbmRlcmlvL21hY2hp" +
			"bmUvaHlwZXJjdWJlL0h5cGVyQ3ViZVJlZ2lzdGVyOwwAIQAiCQAgACMBAApnZXRDaGFubmVsAQAw" +
			"KClMY3JhenlwYW50cy9lbmRlcmlvL21hY2hpbmUvaHlwZXJjdWJlL0NoYW5uZWw7DAAlACYKAAsA" +
			"JwEAEmdldEN1YmVzRm9yQ2hhbm5lbAEAQChMY3JhenlwYW50cy9lbmRlcmlvL21hY2hpbmUvaHlw" +
			"ZXJjdWJlL0NoYW5uZWw7KUxqYXZhL3V0aWwvTGlzdDsMACkAKgoAIAArAQATamF2YS91dGlsL0Fy" +
			"cmF5TGlzdAcALQoALgASAQAOamF2YS91dGlsL0xpc3QHADABAAhpdGVyYXRvcgEAFigpTGphdmEv" +
			"dXRpbC9JdGVyYXRvcjsMADIAMwsAMQA0AQASamF2YS91dGlsL0l0ZXJhdG9yBwA2AQAHaGFzTmV4" +
			"dAEAAygpWgwAOAA5CwA3ADoBAARuZXh0AQAUKClMamF2YS9sYW5nL09iamVjdDsMADwAPQsANwA+" +
			"AQADYWRkAQAVKExqYXZhL2xhbmcvT2JqZWN0OylaDABAAEELADEAQgEABGN1YmUBADRMY3Jhenlw" +
			"YW50cy9lbmRlcmlvL21hY2hpbmUvaHlwZXJjdWJlL1RpbGVIeXBlckN1YmU7AQACaSQBABRMamF2" +
			"YS91dGlsL0l0ZXJhdG9yOwEABGNvbnMBAEZMamF2YS91dGlsL0xpc3Q8TGNyYXp5cGFudHMvZW5k" +
			"ZXJpby9tYWNoaW5lL2h5cGVyY3ViZS9UaWxlSHlwZXJDdWJlOz47AQAQTGphdmEvdXRpbC9MaXN0" +
			"OwEABXRpbGVzAQA3TGphdmEvdXRpbC9MaXN0PExuZXQvbWluZWNyYWZ0L3RpbGVlbnRpdHkvVGls" +
			"ZUVudGl0eTs+OwEAGGdldENvbm5lY3RlZFRyYW5zY2VpdmVycwEAMmNyYXp5cGFudHMvZW5kZXJp" +
			"by9tYWNoaW5lL3RyYW5zY2VpdmVyL0NoYW5uZWxUeXBlBwBOAQAESVRFTQEANExjcmF6eXBhbnRz" +
			"L2VuZGVyaW8vbWFjaGluZS90cmFuc2NlaXZlci9DaGFubmVsVHlwZTsMAFAAUQkATwBSAQASZ2V0" +
			"UmVjaWV2ZUNoYW5uZWxzAQBGKExjcmF6eXBhbnRzL2VuZGVyaW8vbWFjaGluZS90cmFuc2NlaXZl" +
			"ci9DaGFubmVsVHlwZTspTGphdmEvdXRpbC9MaXN0OwwAVABVCgAcAFYBAANnZXQBABUoSSlMamF2" +
			"YS9sYW5nL09iamVjdDsMAFgAWQsAMQBaAQAuY3JhenlwYW50cy9lbmRlcmlvL21hY2hpbmUvdHJh" +
			"bnNjZWl2ZXIvQ2hhbm5lbAcAXAEAPGNyYXp5cGFudHMvZW5kZXJpby9tYWNoaW5lL3RyYW5zY2Vp" +
			"dmVyL1NlcnZlckNoYW5uZWxSZWdpc3RlcgcAXgEAPkxjcmF6eXBhbnRzL2VuZGVyaW8vbWFjaGlu" +
			"ZS90cmFuc2NlaXZlci9TZXJ2ZXJDaGFubmVsUmVnaXN0ZXI7DAAhAGAJAF8AYQEAC2dldEl0ZXJh" +
			"dG9yAQBjKExjcmF6eXBhbnRzL2VuZGVyaW8vbWFjaGluZS90cmFuc2NlaXZlci9DaGFubmVsOylM" +
			"Y29tL2VuZGVyaW8vY29yZS9jb21tb24vdXRpbC9Sb3VuZFJvYmluSXRlcmF0b3I7DABjAGQKAF8A" +
			"ZQEAL2NvbS9lbmRlcmlvL2NvcmUvY29tbW9uL3V0aWwvUm91bmRSb2Jpbkl0ZXJhdG9yBwBnCgBo" +
			"ADQBACNuZXQvbWluZWNyYWZ0L3RpbGVlbnRpdHkvVGlsZUVudGl0eQcAagEAD2dldFNlbmRDaGFu" +
			"bmVscwwAbABVCgAcAG0BAARzaXplAQADKClJDABvAHALADEAcQEABmVxdWFscwwAcwBBCgAEAHQB" +
			"AA9yZWNlaXZlQ2hhbm5lbHMBAEJMamF2YS91dGlsL0xpc3Q8TGNyYXp5cGFudHMvZW5kZXJpby9t" +
			"YWNoaW5lL3RyYW5zY2VpdmVyL0NoYW5uZWw7PjsBAAxzZW5kQ2hhbm5lbHMBAAF0AQA4TGNyYXp5" +
			"cGFudHMvZW5kZXJpby9tYWNoaW5lL3RyYW5zY2VpdmVyL1RpbGVUcmFuc2NlaXZlcjsBAAt0cmFu" +
			"c2NlaXZlcgEAB2NoYW5uZWwBADBMY3JhenlwYW50cy9lbmRlcmlvL21hY2hpbmUvdHJhbnNjZWl2" +
			"ZXIvQ2hhbm5lbDsBABBpc1NlbmRBbmRSZWNlaXZlAQAEQk9USAEAO0xjcmF6eXBhbnRzL2VuZGVy" +
			"aW8vbWFjaGluZS9oeXBlcmN1YmUvVGlsZUh5cGVyQ3ViZSRJb01vZGU7DAB/AIAJAAkAgQEAP0xj" +
			"cmF6eXBhbnRzL2VuZGVyaW8vbWFjaGluZS9oeXBlcmN1YmUvVGlsZUh5cGVyQ3ViZSRTdWJDaGFu" +
			"bmVsOwwAUACDCQAOAIQBABFnZXRNb2RlRm9yQ2hhbm5lbAEAfChMY3JhenlwYW50cy9lbmRlcmlv" +
			"L21hY2hpbmUvaHlwZXJjdWJlL1RpbGVIeXBlckN1YmUkU3ViQ2hhbm5lbDspTGNyYXp5cGFudHMv" +
			"ZW5kZXJpby9tYWNoaW5lL2h5cGVyY3ViZS9UaWxlSHlwZXJDdWJlJElvTW9kZTsMAIYAhwoACwCI" +
			"AQAJaXNFbmRlcklPAQAEQ29kZQEAEkxvY2FsVmFyaWFibGVUYWJsZQEAD0xpbmVOdW1iZXJUYWJs" +
			"ZQEAFkxvY2FsVmFyaWFibGVUeXBlVGFibGUBAA1TdGFja01hcFRhYmxlAQAJU2lnbmF0dXJlAQBe" +
			"KExuZXQvbWluZWNyYWZ0L3RpbGVlbnRpdHkvVGlsZUVudGl0eTspTGphdmEvdXRpbC9MaXN0PExu" +
			"ZXQvbWluZWNyYWZ0L3RpbGVlbnRpdHkvVGlsZUVudGl0eTs+OwEAClNvdXJjZUZpbGUBAAxJbm5l" +
			"ckNsYXNzZXMAIQACAAQAAQAGAAAABwABABAAEQABAIsAAAAvAAEAAQAAAAUqtwATsQAAAAIAjAAA" +
			"AAwAAQAAAAUAFAAVAAAAjQAAAAYAAQAAABMAAQAWABcAAQCLAAAAOQABAAIAAAAFK8EAC6wAAAAC" +
			"AIwAAAAWAAIAAAAFABQAFQAAAAAABQAYABkAAQCNAAAABgABAAAAFwABABoAFwABAIsAAAA5AAEA" +
			"AgAAAAUrwQAcrAAAAAIAjAAAABYAAgAAAAUAFAAVAAAAAAAFABgAGQABAI0AAAAGAAEAAAAcAAEA" +
			"HQAeAAIAiwAAAPAAAgAGAAAASLIAJCvAAAu2ACi2ACxNuwAuWbcAL04suQA1AQA6BBkEuQA7AQCZ" +
			"ACEZBLkAPwEAwAALOgUZBSulAAwtGQW5AEMCAFen/9stsAAAAAQAjAAAAD4ABgA0AA8ARABFAAUA" +
			"HgAoAEYARwAEAAAASAAUABUAAAAAAEgAGAAZAAEADgA6AEgASgACABYAMgBLAEoAAwCOAAAAFgAC" +
			"AA4AOgBIAEkAAgAWADIASwBMAAMAjQAAAB4ABwAAACEADgAiABYAIwA0ACQAOgAlAEMAJwBGACgA" +
			"jwAAABIAA/4AHgcAMQcAMQcANyT6AAIAkAAAAAIAkQABAE0AHgACAIsAAAGcAAMACQAAAKMrwAAc" +
			"TbsALlm3AC9OLLIAU7YAVwO5AFsCAMAAXToEsgBiGQS2AGa2AGk6BRkFuQA7AQCZAG4ZBbkAPwEA" +
			"wAAcOgYZBiymAAan/+QZBrIAU7YAVzoHGQayAFO2AG46CBkHuQByAQAEoAA3GQi5AHIBAASgACwZ" +
			"BBkHA7kAWwIAtgB1mQAcGQQZCAO5AFsCALYAdZkADC0ZBrkAQwIAV6f/ji2wAAAABACMAAAAXAAJ" +
			"AFUASQB2AEoABwBfAD8AeABKAAgAQgBcAHkAegAGACwAdQBGAEcABQAAAKMAFAAVAAAAAACjABgA" +
			"GQABAAUAngB7AHoAAgANAJYASwBKAAMAHwCEAHwAfQAEAI4AAAAgAAMAVQBJAHYAdwAHAF8APwB4" +
			"AHcACAANAJYASwBMAAMAjQAAADIADAAAAC0ABQAuAA0ALwAfADAAQgAxAEgAMgBLADQAVQA1AF8A" +
			"NgCVADcAngA5AKEAOgCPAAAAJwAE/wAsAAYHAAIHAGsHABwHADEHAF0HADcAAPwAHgcAHPoAUvoA" +
			"AgCQAAAAAgCRAAEAfgAXAAEAiwAAAQMAAwAEAAAAbSvBAAuZABmyAIIrwAALsgCFtgCJpgAHBKcA" +
			"BAOsK8EAHJkASivAAByyAFO2AFdNK8AAHLIAU7YAbk4suQByAQAEoAAoLbkAcgEABKAAHiwDuQBb" +
			"AgDAAF0tA7kAWwIAtgB1mQAHBKcABAOsA6wAAAAEAIwAAAAqAAQALwA8AHYASgACADoAMQB4AEoA" +
			"AwAAAG0AFAAVAAAAAABtABgAGQABAI4AAAAWAAIALwA8AHYAdwACADoAMQB4AHcAAwCNAAAAHgAH" +
			"AAAAPwAHAEAAHQBCACQAQwAvAEQAOgBFAGsARwCPAAAAFAAGG0ABAP0ASwcAMQcAMUAB+QAAAAEA" +
			"igA5AAEAiwAAACwAAQABAAAAAgSsAAAAAgCMAAAADAABAAAAAgAUABUAAACNAAAABgABAAAATAAC" +
			"AJIAAAACAAcAkwAAABIAAgAJAAsADEAZAA4ACwAPQBk=";
	protected static final String PREVCLASSDATADEV = "yv66vgAAADIAmQoAGwBMBwBNBwBOCQBPAFAKAAIAUQoATwBSBwBTCgAHAEwLAFQAVQsAVgBXCwBW" +
			"AFgLAFQAWQkAWgBbCgADAFwLAFQAXQcAXgkAXwBgCgBfAGEKAGIAVQoAAwBjCwBUAGQKABsAZQkA" +
			"ZgBnCQBoAGkKAAIAagcAawcAbAcAbQEABjxpbml0PgEAAygpVgEABENvZGUBAA9MaW5lTnVtYmVy" +
			"VGFibGUBABJMb2NhbFZhcmlhYmxlVGFibGUBAAR0aGlzAQArTGxvZ2lzdGljc3BpcGVzL3Byb3h5" +
			"L2VuZGVyaW8vRW5kZXJJT1Byb3h5OwEAC2lzSHlwZXJDdWJlAQAoKExuZXQvbWluZWNyYWZ0L3Rp" +
			"bGVlbnRpdHkvVGlsZUVudGl0eTspWgEABHRpbGUBACVMbmV0L21pbmVjcmFmdC90aWxlZW50aXR5" +
			"L1RpbGVFbnRpdHk7AQANaXNUcmFuc2NlaXZlcgEAFmdldENvbm5lY3RlZEh5cGVyQ3ViZXMBADco" +
			"TG5ldC9taW5lY3JhZnQvdGlsZWVudGl0eS9UaWxlRW50aXR5OylMamF2YS91dGlsL0xpc3Q7AQAE" +
			"Y3ViZQEANExjcmF6eXBhbnRzL2VuZGVyaW8vbWFjaGluZS9oeXBlcmN1YmUvVGlsZUh5cGVyQ3Vi" +
			"ZTsBAAJpJAEAFExqYXZhL3V0aWwvSXRlcmF0b3I7AQAEY29ucwEAEExqYXZhL3V0aWwvTGlzdDsB" +
			"AAV0aWxlcwEAFkxvY2FsVmFyaWFibGVUeXBlVGFibGUBAEZMamF2YS91dGlsL0xpc3Q8TGNyYXp5" +
			"cGFudHMvZW5kZXJpby9tYWNoaW5lL2h5cGVyY3ViZS9UaWxlSHlwZXJDdWJlOz47AQA3TGphdmEv" +
			"dXRpbC9MaXN0PExuZXQvbWluZWNyYWZ0L3RpbGVlbnRpdHkvVGlsZUVudGl0eTs+OwEADVN0YWNr" +
			"TWFwVGFibGUHAG4HAG8BAAlTaWduYXR1cmUBAF4oTG5ldC9taW5lY3JhZnQvdGlsZWVudGl0eS9U" +
			"aWxlRW50aXR5OylMamF2YS91dGlsL0xpc3Q8TG5ldC9taW5lY3JhZnQvdGlsZWVudGl0eS9UaWxl" +
			"RW50aXR5Oz47AQAYZ2V0Q29ubmVjdGVkVHJhbnNjZWl2ZXJzAQAPcmVjZWl2ZUNoYW5uZWxzAQAM" +
			"c2VuZENoYW5uZWxzAQABdAEAOExjcmF6eXBhbnRzL2VuZGVyaW8vbWFjaGluZS90cmFuc2NlaXZl" +
			"ci9UaWxlVHJhbnNjZWl2ZXI7AQALdHJhbnNjZWl2ZXIBAAdjaGFubmVsAQAwTGNyYXp5cGFudHMv" +
			"ZW5kZXJpby9tYWNoaW5lL3RyYW5zY2VpdmVyL0NoYW5uZWw7AQBCTGphdmEvdXRpbC9MaXN0PExj" +
			"cmF6eXBhbnRzL2VuZGVyaW8vbWFjaGluZS90cmFuc2NlaXZlci9DaGFubmVsOz47BwBrBwBwBwBO" +
			"BwBeAQAQaXNTZW5kQW5kUmVjZWl2ZQEACWlzRW5kZXJJTwEAAygpWgEAClNvdXJjZUZpbGUBABFF" +
			"bmRlcklPUHJveHkuamF2YQwAHQAeAQAyY3JhenlwYW50cy9lbmRlcmlvL21hY2hpbmUvaHlwZXJj" +
			"dWJlL1RpbGVIeXBlckN1YmUBADZjcmF6eXBhbnRzL2VuZGVyaW8vbWFjaGluZS90cmFuc2NlaXZl" +
			"ci9UaWxlVHJhbnNjZWl2ZXIHAHEMAHIAcwwAdAB1DAB2AHcBABNqYXZhL3V0aWwvQXJyYXlMaXN0" +
			"BwBuDAB4AHkHAG8MAHoASQwAewB8DAB9AH4HAH8MAIAAgQwAggCDDACEAIUBAC5jcmF6eXBhbnRz" +
			"L2VuZGVyaW8vbWFjaGluZS90cmFuc2NlaXZlci9DaGFubmVsBwCGDAByAIcMAIgAiQcAigwAiwCD" +
			"DACMAI0MAI4AfgcAjwwAkgCTBwCUDACAAJYMAJcAmAEAKWxvZ2lzdGljc3BpcGVzL3Byb3h5L2Vu" +
			"ZGVyaW8vRW5kZXJJT1Byb3h5AQAQamF2YS9sYW5nL09iamVjdAEALWxvZ2lzdGljc3BpcGVzL3By" +
			"b3h5L2ludGVyZmFjZXMvSUVuZGVySU9Qcm94eQEADmphdmEvdXRpbC9MaXN0AQASamF2YS91dGls" +
			"L0l0ZXJhdG9yAQAjbmV0L21pbmVjcmFmdC90aWxlZW50aXR5L1RpbGVFbnRpdHkBADZjcmF6eXBh" +
			"bnRzL2VuZGVyaW8vbWFjaGluZS9oeXBlcmN1YmUvSHlwZXJDdWJlUmVnaXN0ZXIBAAhpbnN0YW5j" +
			"ZQEAOExjcmF6eXBhbnRzL2VuZGVyaW8vbWFjaGluZS9oeXBlcmN1YmUvSHlwZXJDdWJlUmVnaXN0" +
			"ZXI7AQAKZ2V0Q2hhbm5lbAEAMCgpTGNyYXp5cGFudHMvZW5kZXJpby9tYWNoaW5lL2h5cGVyY3Vi" +
			"ZS9DaGFubmVsOwEAEmdldEN1YmVzRm9yQ2hhbm5lbAEAQChMY3JhenlwYW50cy9lbmRlcmlvL21h" +
			"Y2hpbmUvaHlwZXJjdWJlL0NoYW5uZWw7KUxqYXZhL3V0aWwvTGlzdDsBAAhpdGVyYXRvcgEAFigp" +
			"TGphdmEvdXRpbC9JdGVyYXRvcjsBAAdoYXNOZXh0AQAEbmV4dAEAFCgpTGphdmEvbGFuZy9PYmpl" +
			"Y3Q7AQADYWRkAQAVKExqYXZhL2xhbmcvT2JqZWN0OylaAQAyY3JhenlwYW50cy9lbmRlcmlvL21h" +
			"Y2hpbmUvdHJhbnNjZWl2ZXIvQ2hhbm5lbFR5cGUBAARJVEVNAQA0TGNyYXp5cGFudHMvZW5kZXJp" +
			"by9tYWNoaW5lL3RyYW5zY2VpdmVyL0NoYW5uZWxUeXBlOwEAEmdldFJlY2lldmVDaGFubmVscwEA" +
			"RihMY3JhenlwYW50cy9lbmRlcmlvL21hY2hpbmUvdHJhbnNjZWl2ZXIvQ2hhbm5lbFR5cGU7KUxq" +
			"YXZhL3V0aWwvTGlzdDsBAANnZXQBABUoSSlMamF2YS9sYW5nL09iamVjdDsBADxjcmF6eXBhbnRz" +
			"L2VuZGVyaW8vbWFjaGluZS90cmFuc2NlaXZlci9TZXJ2ZXJDaGFubmVsUmVnaXN0ZXIBAD5MY3Jh" +
			"enlwYW50cy9lbmRlcmlvL21hY2hpbmUvdHJhbnNjZWl2ZXIvU2VydmVyQ2hhbm5lbFJlZ2lzdGVy" +
			"OwEAC2dldEl0ZXJhdG9yAQBjKExjcmF6eXBhbnRzL2VuZGVyaW8vbWFjaGluZS90cmFuc2NlaXZl" +
			"ci9DaGFubmVsOylMY29tL2VuZGVyaW8vY29yZS9jb21tb24vdXRpbC9Sb3VuZFJvYmluSXRlcmF0" +
			"b3I7AQAvY29tL2VuZGVyaW8vY29yZS9jb21tb24vdXRpbC9Sb3VuZFJvYmluSXRlcmF0b3IBAA9n" +
			"ZXRTZW5kQ2hhbm5lbHMBAARzaXplAQADKClJAQAGZXF1YWxzAQA5Y3JhenlwYW50cy9lbmRlcmlv" +
			"L21hY2hpbmUvaHlwZXJjdWJlL1RpbGVIeXBlckN1YmUkSW9Nb2RlAQAGSW9Nb2RlAQAMSW5uZXJD" +
			"bGFzc2VzAQAEQk9USAEAO0xjcmF6eXBhbnRzL2VuZGVyaW8vbWFjaGluZS9oeXBlcmN1YmUvVGls" +
			"ZUh5cGVyQ3ViZSRJb01vZGU7AQA9Y3JhenlwYW50cy9lbmRlcmlvL21hY2hpbmUvaHlwZXJjdWJl" +
			"L1RpbGVIeXBlckN1YmUkU3ViQ2hhbm5lbAEAClN1YkNoYW5uZWwBAD9MY3JhenlwYW50cy9lbmRl" +
			"cmlvL21hY2hpbmUvaHlwZXJjdWJlL1RpbGVIeXBlckN1YmUkU3ViQ2hhbm5lbDsBABFnZXRNb2Rl" +
			"Rm9yQ2hhbm5lbAEAfChMY3JhenlwYW50cy9lbmRlcmlvL21hY2hpbmUvaHlwZXJjdWJlL1RpbGVI" +
			"eXBlckN1YmUkU3ViQ2hhbm5lbDspTGNyYXp5cGFudHMvZW5kZXJpby9tYWNoaW5lL2h5cGVyY3Vi" +
			"ZS9UaWxlSHlwZXJDdWJlJElvTW9kZTsAIQAaABsAAQAcAAAABwABAB0AHgABAB8AAAAvAAEAAQAA" +
			"AAUqtwABsQAAAAIAIAAAAAYAAQAAABMAIQAAAAwAAQAAAAUAIgAjAAAAAQAkACUAAQAfAAAAOQAB" +
			"AAIAAAAFK8EAAqwAAAACACAAAAAGAAEAAAAXACEAAAAWAAIAAAAFACIAIwAAAAAABQAmACcAAQAB" +
			"ACgAJQABAB8AAAA5AAEAAgAAAAUrwQADrAAAAAIAIAAAAAYAAQAAABwAIQAAABYAAgAAAAUAIgAj" +
			"AAAAAAAFACYAJwABAAEAKQAqAAIAHwAAAPAAAgAGAAAASLIABCvAAAK2AAW2AAZNuwAHWbcACE4s" +
			"uQAJAQA6BBkEuQAKAQCZACEZBLkACwEAwAACOgUZBSulAAwtGQW5AAwCAFen/9stsAAAAAQAIAAA" +
			"AB4ABwAAACEADgAiABYAIwA0ACQAOgAlAEMAJwBGACgAIQAAAD4ABgA0AA8AKwAsAAUAHgAoAC0A" +
			"LgAEAAAASAAiACMAAAAAAEgAJgAnAAEADgA6AC8AMAACABYAMgAxADAAAwAyAAAAFgACAA4AOgAv" +
			"ADMAAgAWADIAMQA0AAMANQAAABIAA/4AHgcANgcANgcANyT6AAIAOAAAAAIAOQABADoAKgACAB8A" +
			"AAGcAAMACQAAAKMrwAADTbsAB1m3AAhOLLIADbYADgO5AA8CAMAAEDoEsgARGQS2ABK2ABM6BRkF" +
			"uQAKAQCZAG4ZBbkACwEAwAADOgYZBiymAAan/+QZBrIADbYADjoHGQayAA22ABQ6CBkHuQAVAQAE" +
			"oAA3GQi5ABUBAASgACwZBBkHA7kADwIAtgAWmQAcGQQZCAO5AA8CALYAFpkADC0ZBrkADAIAV6f/" +
			"ji2wAAAABAAgAAAAMgAMAAAALQAFAC4ADQAvAB8AMABCADEASAAyAEsANABVADUAXwA2AJUANwCe" +
			"ADkAoQA6ACEAAABcAAkAVQBJADsAMAAHAF8APwA8ADAACABCAFwAPQA+AAYALAB1AC0ALgAFAAAA" +
			"owAiACMAAAAAAKMAJgAnAAEABQCeAD8APgACAA0AlgAxADAAAwAfAIQAQABBAAQAMgAAACAAAwBV" +
			"AEkAOwBCAAcAXwA/ADwAQgAIAA0AlgAxADQAAwA1AAAAJwAE/wAsAAYHAEMHAEQHAEUHADYHAEYH" +
			"ADcAAPwAHgcARfoAUvoAAgA4AAAAAgA5AAEARwAlAAEAHwAAAQMAAwAEAAAAbSvBAAKZABmyABcr" +
			"wAACsgAYtgAZpgAHBKcABAOsK8EAA5kASivAAAOyAA22AA5NK8AAA7IADbYAFE4suQAVAQAEoAAo" +
			"LbkAFQEABKAAHiwDuQAPAgDAABAtA7kADwIAtgAWmQAHBKcABAOsA6wAAAAEACAAAAAeAAcAAAA/" +
			"AAcAQAAdAEIAJABDAC8ARAA6AEUAawBHACEAAAAqAAQALwA8ADsAMAACADoAMQA8ADAAAwAAAG0A" +
			"IgAjAAAAAABtACYAJwABADIAAAAWAAIALwA8ADsAQgACADoAMQA8AEIAAwA1AAAAFAAGG0ABAP0A" +
			"SwcANgcANkAB+QAAAAEASABJAAEAHwAAACwAAQABAAAAAgSsAAAAAgAgAAAABgABAAAATAAhAAAA" +
			"DAABAAAAAgAiACMAAAACAEoAAAACAEsAkQAAABIAAgBmAAIAkEAZAGgAAgCVQBk=";
}
